absBestLFC: 1
bamExt: .filtered.bam
baseDir: /data/manke/sikora/miniconda3/envs/snakemake/lib/python3.6/site-packages/snakePipes
bigWigType: both
bwBinSize: 25
clusterConfig: shared/cluster.yaml
clusterConfigFile: null
configFile: null
createDAG: false
emailAddress: null
emailSender: null
fdr: 0.05
filterGTF: null
fragmentLength: 200
fromBAM: /data/manke/sikora/snakepipes/BAM_input/filtered_bam
genome: /data/manke/sikora/snakepipes/.ci_stuff/organism.yaml
keepTemp: false
local: false
maxJobs: 5
mfold: 0 50
onlySSL: false
organismsDir: shared/organisms
outdir: /data/manke/sikora/snakepipes/BAM_input
pairedEnd: true
peakCaller: MACS2
pipeline: chip-seq
plotFormat: png
predictChIPDict: null
qval: 0.001
sampleSheet: /data/manke/sikora/snakepipes/.ci_stuff/test_sampleSheet.tsv
samples_config: /data/manke/sikora/snakepipes/.ci_stuff/ChIP.sample_config.yaml
smtpPassword: null
smtpPort: 0
smtpServer: null
smtpUsername: null
snakemakeOptions: ' --use-conda --conda-prefix /package/anaconda3/envs/   --dryrun
  --conda-prefix /tmp'
tempDir: /data/extended/
toolsVersion: true
verbose: false
windowSize: 150
workingdir: /data/manke/sikora/snakepipes/BAM_input
