name: linux

on: 
  push:
    branches: [dev_wd]

defaults:
  run:
      shell: bash -l {0}


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: .github/snakePipesEnvCI.yml
        cache-downloads: true
    - name: Install snakePipes
      run: |
        micromamba run -n snakePipes_CI python -m pip install . --no-deps --ignore-installed -vvv
    - name: docs
      run: |
        micromamba activate snakePipes_CI
        cd docs
        make html
  flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: .github/snakePipesEnvCI.yml
        cache-downloads: true
    - name: Install snakePipes
      run: |
        micromamba run -n snakePipes_CI python -m pip install . --no-deps --ignore-installed -vvv
    - name: flake
      run: |
        micromamba activate snakePipes_CI
        flake8 --ignore=E501,E722,E402 --exclude docs/conf.py .
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: .github/snakePipesEnvCI.yml
        cache-downloads: true
    - name: Install snakePipes
      run: |
        micromamba run -n snakePipes_CI python -m pip install . --no-deps --ignore-installed -vvv
    - name: CI
      run: |
        micromamba activate snakePipes_CI
        ./.ci_stuff/test_dag.sh
  createEnvs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: .github/snakePipesEnvCI.yml
        cache-downloads: true
    - name: install snakePipes
      run: |
        micromamba run -n snakePipes_CI python -m pip install . --no-deps --ignore-installed -vvv
    - name: createEnvs
      run: |
        snakePipes createEnvs --force

